### ISSUE TITLE
UBSAN error; reference binding to null pointer

### ISSUE THREAD

**Issue by jeroen** [r-dbi/RPostgres#156]
CRAN reports undefined behavior:

```
> test_check("RPostgres")
/usr/local/bin/../include/c++/v1/vector:1493:12: runtime error: reference binding to null pointer of type 'const char *'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/local/bin/../include/c++/v1/vector:1493:12 in 
/usr/local/bin/../include/c++/v1/vector:1493:12: runtime error: reference binding to null pointer of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/local/bin/../include/c++/v1/vector:1493:12 in 
testthat results ================================================================
```

```
> ### ** Examples
> 
> if (postgresHasDefault()) {
+ library(DBI)
+ # Pass more arguments as necessary to dbConnect()
+ con <- dbConnect(RPostgres::Postgres())
+ dbDisconnect(con)
+ }
/usr/local/bin/../include/c++/v1/vector:1493:12: runtime error: reference binding to null pointer of type 'const char *'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/local/bin/../include/c++/v1/vector:1493:12 in 
/usr/local/bin/../include/c++/v1/vector:1493:12: runtime error: reference binding to null pointer of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/local/bin/../include/c++/v1/vector:1493:12 in 
```

```
> ### ** Examples
> 
> if (postgresHasDefault()) {
+ library(DBI)
+ # Pass more arguments as necessary to dbConnect()
+ con <- dbConnect(RPostgres::Postgres())
+ dbDisconnect(con)
+ }
/usr/include/c++/7/bits/stl_vector.h:798:34: runtime error: reference binding to null pointer of type 'int'
/usr/include/c++/7/bits/stl_vector.h:798:34: runtime error: reference binding to null pointer of type 'int'
/usr/include/c++/7/bits/stl_vector.h:798:34: runtime error: reference binding to null pointer of type 'const char *'
```

**Comment by jeroen** [comment]
Here are some strak traces:


```
> library(RPostgres)
po> postgresHasDefault()
/usr/include/c++/6/bits/stl_vector.h:781:41: runtime error: reference binding to null pointer of type 'value_type'
    #0 0x7f412beb0b7b in PqResultImpl::bind_row() (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x2f9b7b)
    #1 0x7f412beb674e in PqResultImpl::bind(Rcpp::Vector<19, Rcpp::PreserveStorage> const&) (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x2ff74e)
    #2 0x7f412beb6bd9 in PqResultImpl::bind() (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x2ffbd9)
    #3 0x7f412bebdb6a in PqResultImpl::PqResultImpl(DbResult*, pg_conn*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x306b6a)
    #4 0x7f412be89755 in DbResult::DbResult(boost::shared_ptr<DbConnection> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x2d2755)
    #5 0x7f412bf1020f in result_create(Rcpp::XPtr<boost::shared_ptr<DbConnection>, Rcpp::PreserveStorage, &(void Rcpp::standard_delete_finalizer<boost::shared_ptr<DbConnection> >(boost::shared_ptr<DbConnection>*)), false>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x35920f)
    #6 0x7f412bee287f in _RPostgres_result_create (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x32b87f)
```


```
/usr/include/c++/6/bits/stl_vector.h:781:41: runtime error: reference binding to null pointer of type 'value_type'
    #0 0x7f412beb0b5b in PqResultImpl::bind_row() (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x2f9b5b)
    #1 0x7f412beb674e in PqResultImpl::bind(Rcpp::Vector<19, Rcpp::PreserveStorage> const&) (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x2ff74e)
    #2 0x7f412beb6bd9 in PqResultImpl::bind() (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x2ffbd9)
    #3 0x7f412bebdb6a in PqResultImpl::PqResultImpl(DbResult*, pg_conn*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x306b6a)
    #4 0x7f412be89755 in DbResult::DbResult(boost::shared_ptr<DbConnection> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x2d2755)
    #5 0x7f412bf1020f in result_create(Rcpp::XPtr<boost::shared_ptr<DbConnection>, Rcpp::PreserveStorage, &(void Rcpp::standard_delete_finalizer<boost::shared_ptr<DbConnection> >(boost::shared_ptr<DbConnection>*)), false>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x35920f)
    #6 0x7f412bee287f in _RPostgres_result_create (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x32b87f)
```

```
/usr/include/c++/6/bits/stl_vector.h:781:41: runtime error: reference binding to null pointer of type 'const char *'
    #0 0x7f412beb0b3b in PqResultImpl::bind_row() (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x2f9b3b)
    #1 0x7f412beb674e in PqResultImpl::bind(Rcpp::Vector<19, Rcpp::PreserveStorage> const&) (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x2ff74e)
    #2 0x7f412beb6bd9 in PqResultImpl::bind() (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x2ffbd9)
    #3 0x7f412bebdb6a in PqResultImpl::PqResultImpl(DbResult*, pg_conn*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x306b6a)
    #4 0x7f412be89755 in DbResult::DbResult(boost::shared_ptr<DbConnection> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x2d2755)
    #5 0x7f412bf1020f in result_create(Rcpp::XPtr<boost::shared_ptr<DbConnection>, Rcpp::PreserveStorage, &(void Rcpp::standard_delete_finalizer<boost::shared_ptr<DbConnection> >(boost::shared_ptr<DbConnection>*)), false>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x35920f)
    #6 0x7f412bee287f in _RPostgres_result_create (/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so+0x32b87f)
```

**Comment by jeroen** [comment]
Fixed via https://github.com/r-dbi/RPostgres/commit/a98db282adf2437fb42e383307715ba1c39145cd. You should not create a pointer to the first element of a zero-length vector.
